# Generated by Django 4.2.5 on 2023-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
